# Generated by Django 4.2.5 on 2023-11-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='title',
            field=models.CharField(choices=[('Cordination and Control', 'Cordination and controll'), ('First Aid', 'First Aid'), ('Food Security', 'Food Security'), ('Remedial', 'Remedial'), ('Health', 'Health')], max_length=100),
        ),
    ]
